
data:
  dynamic-plugins.yaml: |
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      - package: ./dynamic-plugins/dist/backstage-plugin-kubernetes-backend-dynamic
        disabled: false
        pluginConfig:
          kubernetes:
            customResources:
              - group: 'tekton.dev'
                apiVersion: 'v1'
                plural: 'pipelines'
              - group: 'tekton.dev'
                apiVersion: 'v1'
                plural: 'pipelineruns'
              - group: 'tekton.dev'
                apiVersion: 'v1'
                plural: 'taskruns'
              - group: 'route.openshift.io'
                apiVersion: 'v1'
                plural: 'routes'
            serviceLocatorMethod:
              type: 'multiTenant'
            clusterLocatorMethods:
              - type: 'config'
                clusters:
                  - name: 'OpenShift Orchestrator Demo'
                    url: ${K8S_CLUSTER_URL}
                    authProvider: 'serviceAccount'
                    skipTLSVerify: true
                    serviceAccountToken: ${K8S_CLUSTER_TOKEN}
      - package: ./dynamic-plugins/dist/backstage-plugin-kubernetes
        disabled: false
        pluginConfig:
          dynamicPlugins:
            frontend:
              backstage.plugin-kubernetes:
                mountPoints:
                  - mountPoint: entity.page.kubernetes/cards
                    importName: EntityKubernetesContent
                    config:
                      layout:
                        gridColumn: "1 / -1"
                      if:
                        anyOf:
                          - hasAnnotation: backstage.io/kubernetes-id
                          - hasAnnotation: backstage.io/kubernetes-namespace
      - disabled: false
        package: "https://github.com/batzionb/pluginrelease/releases/download/backend-1.2.0-rc.1/backstage-plugin-orchestrator-backend-dynamic-1.2.0-rc.1.tgz"
        integrity: sha512-uF7BVOTQEofTyKGvEW7ipPhbHCjsXw8wvSx1YyAQDSsVgq7l6FckUZN2jT0kXmiGqH2f7C7+xKIA
        pluginConfig:
          orchestrator:
            dataIndexService:
              url: http://sonataflow-platform-data-index-service.sonataflow-infra
      - disabled: false
        package: "https://github.com/batzionb/pluginrelease/releases/download/1.2.0-rc.1/backstage-plugin-orchestrator-1.2.0-rc.1.tgz"
        integrity: sha512-4C3ZeaGeJdrDWRlWGm1sxiZrfn5cIYynlIsKCcKq+aGpZKJABaKesuvGScBX++jmTbCUMDwPXZmW
        pluginConfig:
          dynamicPlugins:
            frontend:
              janus-idp.backstage-plugin-orchestrator:
                appIcons:
                  - importName: OrchestratorIcon
                    module: OrchestratorPlugin
                    name: orchestratorIcon
                dynamicRoutes:
                  - importName: OrchestratorPage
                    menuItem:
                      icon: orchestratorIcon
                      text: Orchestrator
                    module: OrchestratorPlugin
                    path: /orchestrator
      - disabled: false
        package: https://github.com/mareklibra/gh-pages/raw/main/download/002/plugin-notifications-dynamic-0.2.0-redhat.10001.tgz
        integrity: sha512-Rq/Nn3N/y94t4oeQagW+o8YwTUVXt8utSkKGJVAa3AGrnXs6FkMCb5Moy0CoYUom5ld4O2Mw0EHoaAgmm/IvWg==
        pluginConfig:
          dynamicPlugins:
            frontend:
              redhat.plugin-notifications:
                dynamicRoutes:
                  - importName: NotificationsPage
                    menuItem:
                      config:
                        props:
                          titleCounterEnabled: true
                          webNotificationsEnabled: false
                      importName: NotificationsSidebarItem
                    path: /notifications
      - disabled: false
        package: https://github.com/mareklibra/gh-pages/raw/main/download/002/plugin-signals-dynamic-0.0.5-redhat.10001.tgz
        integrity: sha512-aAYWPyTA113RbgZsGdWScVaQ2M6JZRmA7yMDpFR1QVJFn9FdqD41u37GUNKcSbpOCSZogH0d91d5QNECSX667g==
        pluginConfig:
          dynamicPlugins:
            frontend:
              redhat.plugin-signals: {}
      - disabled: false
        package: https://github.com/mareklibra/gh-pages/raw/main/download/002/plugin-notifications-backend-dynamic-0.2.0-redhat.10001.tgz
        integrity: sha512-MiST7VKvqombWKPdmPpdO1nLc9BCsEJTIwg6wUTbT/uu3YOiQg/0U8JBjY3wihJp/iEb+pwAyDysbq8Uqz11Hg==
      - disabled: false
        package: https://github.com/mareklibra/gh-pages/raw/main/download/002/plugin-signals-backend-dynamic-0.1.3-redhat.10001.tgz
        integrity: sha512-fd9OLCFZZV5fVDDihPETxTnhc/AKUAKETnAR15vL0qOcHEpersytVogOTdS07YSiNLcFjMXl+YJi9xVLfxBHWw==
